export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';

export const FETCH_ALBOMS_FOR_USER_SUCCESS = 'FETCH_ALBOMS_FOR_USER_SUCCESS';
export const FETCH_ALBOMS_FOR_USER_FAIL = 'FETCH_ALBOMS_FOR_USER_FAIL';

export const FETCH_FILMS_START = 'FETCH_FILMS_START';
export const FETCH_FILMS_SUCCESS= 'FETCH_FILMS_SUCCESS';
export const FETCH_TOP_FILMS_SUCCESS= 'FETCH_FILMS_SUCCESS';
export const FETCH_FILMS_FAIL = 'FETCH_FILMS_FAIL';

